サーバーのコンソール上にログ出力するオプションを追加
akashic-games/akashic-cli-serve pull request #1
Opened 2019-01-30 10:57 UTC by dera-

### 概要
今までは、無条件でサーバーのコンソール上にログ出力していましたが、出力するオプション(--verbose)を追加して、それが指定された時だけ全ログが出力されるようになります。エラーと起動時のログについてはオプションを指定しなくても出力されるようにしました

### やったこと
* --verboseオプションの追加
* akashic-cli-serveとheadless-driverの出力するログには色を付けるようにした
  * info, debug: 灰色
  * wran: 黄色
  * error: 赤
  * 起動時: 緑

2019-01-30 11:52 UTC, xnv requested changes

2019-01-30 11:52 UTC, xnv commented on src/server/index.ts
> +				// {}だけだとtslintでエラーになるのでコメントアウトだけ入れる
デフォルトなら warn も出したいです。 `--quiet` なら潰しても良さそうですが。

2019-01-30 11:52 UTC, xnv commented on src/server/index.ts
> +				// {}だけだとtslintでエラーになるのでコメントアウトだけ入れる
これこの lint 設定が理不尽なような……

2019-01-30 11:52 UTC, xnv commented on src/server/index.ts
> +function convertStrings(params: any[]): string[] {
export するでもないしこだわりませんが、文字列群をコンバートするのではなく文字列群にコンバートするんでしょうから `convertToStrings()` の方が意図に沿うのではありませんか。

2019-01-30 11:52 UTC, xnv commented on src/server/index.ts
> +		setSystemLogger({
headless-driver 側の話ですが、「エラーではないけど必ず表示してほしい」みたいな場合に使うものをつけておきたい気がしますねえ。(正常系の出力方法が握りつぶされうるものしかなくなってしまう)

2019-01-30 11:52 UTC, xnv commented on src/server/index.ts
> +		.option("-v, --verbose", `display detail information on console.`)
- 文頭大文字でお願いします。
- detail は動詞・名詞なのでここで使うなら detailed では。

2019-01-30 11:52 UTC, xnv commented on src/server/index.ts
> +import * as util from "util";
気持ちの問題なんですが、 import 順が コアモジュール → サードパーティnpmモジュール → 我々のnpmモジュール → このモジュール内 という順序になっているので合わせてもらいたいです。

2019-01-31 01:53 UTC, yu-ogi commented on src/server/controller/SandboxConfigController.ts
> +					getSystemLogger().error("Failure to load sandbox.config.json.", e.code);
こちら側から `setSystemLogger()` でロガーを挿入しているので、 `getSystemLogger()` を使うと相互参照のような形になるのが気になります。
( `setSystemLogger()` より先に `getSystemLogger()` を参照すると akashic-cli-serve 側でキャッチできなくなる = ランタイムで動作が変わりうる)

akashic-cli-serve 側で定義したロガーを内部で参照する形のほうが簡潔になりそうに思いましたがいかがでしょう。

2019-01-31 01:53 UTC, yu-ogi commented on src/server/domain/SocketIOAMFlowManager.ts
> +			getSystemLogger().info("a user connected. playId: " + playId);
このあたりも同様です。

2019-01-31 06:37 UTC, dera- commented on src/server/index.ts
> +				// {}だけだとtslintでエラーになるのでコメントアウトだけ入れる
warnも出すように修正しておきます

2019-01-31 07:06 UTC, dera- commented on src/server/index.ts
> +				// {}だけだとtslintでエラーになるのでコメントアウトだけ入れる
ではlintの設定の方を直してみます

2019-01-31 07:06 UTC, dera- commented on src/server/index.ts
> +function convertStrings(params: any[]): string[] {
完全に英語を誤ってました。。修正しておきます

2019-01-31 07:17 UTC, dera- commented on src/server/index.ts
> +		.option("-v, --verbose", `display detail information on console.`)
こちらのオプションの説明も修正します

2019-01-31 07:20 UTC, dera- commented on src/server/index.ts
> +		setSystemLogger({
SystemLoggerにエラーではない情報を必ず表示するメソッドを新しく定義する感じですかね？であれば、それについては別途対応にしようかと思いますがどうでしょうか？

2019-01-31 07:21 UTC, dera- commented on src/server/index.ts
> +import * as util from "util";
あ、、utilがコアモジュールであることを失念していました。こちら修正しようと思います

2019-01-31 07:32 UTC, dera- commented on src/server/controller/SandboxConfigController.ts
> +					getSystemLogger().error("Failure to load sandbox.config.json.", e.code);
うーん、認識が間違っていたら申し訳ないのですが、`setSystemLogger()`の呼び出しはサーバー起動時にエントリーポイントで行っているので、`setSystemLogger()`より先に`getSystemLogger()`が呼ばれることはないと思うんですよね。。
また、そのことを心配するのであれば、akashic-cli-serve 側でロガーを定義した場合でも定義前にロガーが呼び出されるのではという懸念も生まれると思いますので、akashic-cli-serve 側で定義することにそれほどメリットは感じていないですね。。

2019-01-31 07:58 UTC, yu-ogi commented on src/server/controller/SandboxConfigController.ts
> +					getSystemLogger().error("Failure to load sandbox.config.json.", e.code);
内部のメソッドを呼び出すのに外部のライブラリを経由しているという点が気になりコメントいたしました。
特に気にならないようでしたら無視してください。

2019-01-31 08:03 UTC, yu-ogi approved these changes

2019-02-01 12:37 UTC, xnv approved these changes

2019-02-06 03:30 UTC, merged