サーバー起動時にホスト名を指定しないとホストPC以外でアクセスできなくなる問題の修正
akashic-games/akashic-cli-serve pull request #2
Opened 2019-01-31 11:02 UTC by dera-

### 概要
やりたいことはタイトルの通り。原因はサーバー起動時のホストとポート番号を /config/content.jsonや/config/content.raw.json中のURLのベースURLとしてそのまま使い回しているせいで、ホストPC以外のPCでアクセスした時でもhttp://localhost:3300/~~といったURLにアクセスしようとしてしまうため。

### やったこと
* 一部URLを以下のように変更
  * /config/engine => /config/content.json
  * /config/engine/raw => /config/content.raw.json
* サーバー起動時にホストやポート番号が指定されない場合、/config/content.jsonや/config/content.raw.json中のURLのベースURLをリクエスト元のURLと同一のものにする対応
* globalの利用をやめて代わりに、新たに作成したServerGlobalOptionを利用するようにした

2019-01-31 11:05 UTC, dera- commented on src/server/controller/ConfigController.ts
> +export const createHandlerToGetEngineConfig = (isRaw: boolean): express.RequestHandler => {
handleToGetEngineConfig とhandleToGetRawEngineConfig はほぼ同一の処理をしていたので、1つの関数にまとめてしまいました。isRawは外から渡す必要があるのでハンドラを生成する形になってしまいましたが。。

2019-01-31 11:08 UTC, dera- commented on src/server/controller/ConfigController.ts
> +				throw new BadRequestError({ errorMessage: "portNumber is undefined" });
ここがBadRequestErrorでいいのか正直あまり自信がありません。
そもそもこのエラーは起こらない想定でいますので、要らないのではとすら思っていますが。。

2019-01-31 11:09 UTC, dera- commented on src/server/index.ts
> +	if (commander.port && isNaN(commander.port)) {
commander.portには直接デフォルト値が入らなくなったので、ここの条件も修正しました

2019-01-31 12:21 UTC, xnv requested changes

2019-01-31 12:21 UTC, xnv commented on src/server/controller/ConfigController.ts
> +				throw new BadRequestError({ errorMessage: "portNumber is undefined" });
引数に `--port 80` をつけられたら 80 で起動するのでは。ここに値がないんなら出力からもなくなればいいだけではないでしょうか。

2019-01-31 12:21 UTC, xnv commented on src/server/domain/EngineConfig.ts
> +export const getEngineConfig = (host: string, port: number, isRaw: boolean): EngineConfig => {
- 引数渡して使われないってのも大分直感に反しますし、host の解決は外側でやりませんか。
- (後から変えにくいオプション名だけ先に変えておいたんですが) `hostname` と `host` を区別したいです。`req.header("host")` (host) を split したら host と port になるの、理解しにくいので……。

2019-01-31 12:21 UTC, xnv commented on CHANGELOG.md
> +* 一部URLを以下のように変更
s/一部URL/内部APIのエンドポイント/ とかですかね？　ユーザ影響がない変更なので、そのことが伝わるような書き方(内部って書いてあるとか)になるといい気がします。

2019-02-01 03:33 UTC, yu-ogi commented on src/server/index.ts
> +import {DEFAULT_HOST, DEFAULT_PORT, serverGlobalOption} from "./common/ServerGlobalOption";
`serverGlobalOption` にすでに `DEFAULT_HOST`, `DEFAULT_PORT` が代入されているのにそれぞれ個別に import している意図って何でしょう?

2019-02-01 03:33 UTC, yu-ogi commented on src/server/common/ServerGlobalOption.ts
> +	useRequestedPort: boolean;
- `useRequested...` の存在意義って何でしょう?
   - `/src/server/index.ts` で `serverGlobalOption.host` `serverGlobalOption.port` を直接変更しているのでよくわからないです
- `host` や `port` などの静的な情報は `option` よりも `config` のほうが個人的にはしっくりくるように思いました。

2019-02-01 03:33 UTC, yu-ogi commented on src/server/domain/EngineConfig.ts
> +	const portNumber = serverGlobalOption.useRequestedPort ? serverGlobalOption.port : port;
akashic-cli-serve のモデルを理解できているわけでは無いですが、 `host` `port` の解決を domain が解決するのは直感に反しているような気がしています。

2019-02-01 03:33 UTC, yu-ogi commented on src/server/controller/ConfigController.ts
> +				throw new BadRequestError({ errorMessage: "portNumber is undefined" });
- `Controller` はどのようなリクエストが来るかがわからないため、基本的にはエラー処理が必要かと思います。
- 「80番ポート (:80 が省略された場合) に起動できない」のは akashic-cli-serve の仕様の問題なので `500` エラーが適切かと思います。

2019-02-01 07:13 UTC, dera- commented on src/server/controller/ConfigController.ts
> +				throw new BadRequestError({ errorMessage: "portNumber is undefined" });
一般ユーザーだと1023番ポートまで起動することはできないみたいなので、80番ポートでの起動もしないこと前提にしてしまっていいかなと考えたところです(rootユーザーで起動すれば80番ポートでの起動もできるそうですが。。)
こちら400ではなく500エラーを返すように修正しておきます

2019-02-01 07:14 UTC, dera- commented on src/server/domain/EngineConfig.ts
> +export const getEngineConfig = (host: string, port: number, isRaw: boolean): EngineConfig => {
hostの解決はコントローラー側で行ってこのメソッドにはhost(ベースURL)を渡す仕組みにしようと思います

2019-02-01 07:15 UTC, dera- commented on CHANGELOG.md
> +* 一部URLを以下のように変更
承知しました、そのように修正します

2019-02-01 07:41 UTC, dera- commented on src/server/index.ts
> +import {DEFAULT_HOST, DEFAULT_PORT, serverGlobalOption} from "./common/ServerGlobalOption";
オプションのデフォルト値の説明で必要でしたが、serverGlobalOptionで充分代用できるものでしたので、これらimportしないように修正しました

2019-02-01 07:51 UTC, dera- commented on src/server/common/ServerGlobalOption.ts
> +	useRequestedPort: boolean;
interface名とファイル名をServerGlobalConfigに変更しました。

`useRequested...` は/config/content.jsonの中身のURL(content_url)などのベースURLを決定するために必要ですね。どこにも明記していなくて申し訳ないのですが、そのベースURLは以下の仕様で生成しようと思っています。
* 起動オプションでホスト名・ポート番号が指定されていたらそれをそれぞれ利用して、指定されていなければリクエスト元のものを使う。
利用箇所が限定的な変数ですが、指定されているかどうかがhostNameとportだけでは分からない状態だったので用意しました。

2019-02-01 07:52 UTC, dera- commented on src/server/domain/EngineConfig.ts
> +	const portNumber = serverGlobalOption.useRequestedPort ? serverGlobalOption.port : port;
こちら、コントローラー側で解決するように修正しました。

2019-02-01 12:47 UTC, xnv approved these changes

2019-02-01 12:47 UTC, xnv commented on src/server/common/ServerGlobalConfig.ts
> +	hostName: string;
この `host`, `hostname` の使い分けはなんとなくブラウザの `window.location.host`, 同 `hostname` に由来してるつもりなので、 `hostName` ではなく `hostname` にしておきたいです。

2019-02-01 12:47 UTC, xnv commented on src/server/controller/ConfigController.ts
> +				throw new InternalServerError({ errorMessage: "can not connect to port 80" });
80 番ポートで一般ユーザが起動できないとしても、sudo されない保証もないので、ここで問答無用でエラーにする理由にはならないと思います。 (80で立ち上げるのは避けるべき気もしますが、そのことは「起動時に警告メッセージが出る」とかで対応すべきであって、ここでまるで何かのバグに見えてしまうようなエラーの出させ方をしても嬉しくはないでしょう)

2019-02-01 12:50 UTC, xnv commented
別リポジトリになりますが、 https://akashic-games.github.io/guide/akashic-cli.html これの記述の修正もお願いしたいです。

2019-02-04 00:58 UTC, yu-ogi approved these changes

2019-02-04 00:58 UTC, yu-ogi commented on src/server/controller/ConfigController.ts
> +			const hostname = serverGlobalConfig.useRequestedHostname ? serverGlobalConfig.hostname : urlInfo[0];
`useRequested...` の `Request` は HTTP のリクエスト (`req`) ではなく起動時に `--host` を指定したかどうかという値なんですね。
第三者がこのコードをいじることを前提にするのであれば、コメントで補足したほうが良いかと思います。

2019-02-04 03:25 UTC, dera- commented on src/server/common/ServerGlobalConfig.ts
> +	hostName: string;
こちら修正しました

2019-02-04 03:35 UTC, dera- commented on src/server/controller/ConfigController.ts
> +				throw new InternalServerError({ errorMessage: "can not connect to port 80" });
ポート番号が見つからなければここでエラーを出すのではなく、80番ポートになるように修正します。また、80番ポートで起動時は警告を表示するようにしました

2019-02-04 03:37 UTC, dera- commented on src/server/controller/ConfigController.ts
> +			const hostname = serverGlobalConfig.useRequestedHostname ? serverGlobalConfig.hostname : urlInfo[0];
そのあたりの補足をServerGlobalOptionに記述しておきます

2019-02-05 05:58 UTC, dera- commented on src/client/bootstrap.tsx
> +	clientContentUrl: "/config/content.json"  // 絶対パスを渡すとそれがPlayのclientContentUrlとしてサーバーに記録され全クライアントでそのURLが使われることになるのでここでは相対パスを渡す。
最初にゲームを起動したクライアントのベースURLが`localhost:3300`だった時、次にアクセスするクライアントでベースURLがIPだとしても`http://localhost:3300/config/content.json`にアクセスしてしまう問題が残っていたので、上記に書いたような対応を行いました

2019-02-05 06:10 UTC, yu-ogi commented on src/client/store/LocalInstanceEntity.ts
> +		this.contentUrl = window.location.origin + params.contentUrl; // contentUrlは相対パスになっているので絶対パスにする
ここの差分って必要ですかね?

2019-02-05 06:19 UTC, yu-ogi commented on src/client/bootstrap.tsx
> +	clientContentUrl: "/config/content.json"  // 絶対パスを渡すとそれがPlayのclientContentUrlとしてサーバーに記録され全クライアントでそのURLが使われることになるのでここでは相対パスを渡す。
(nits) `相対パス` というよりかは `ルートパス` なような気がしますね。

2019-02-05 06:31 UTC, dera- commented on src/client/store/LocalInstanceEntity.ts
> +		this.contentUrl = window.location.origin + params.contentUrl; // contentUrlは相対パスになっているので絶対パスにする
agvに渡すcontenturlは絶対パスである必要があると思ってこのような処理を行いましたが、試してみたところルートパスでも問題なさそうだったのでこの差分は消しておきます

2019-02-05 06:32 UTC, dera- commented on src/client/bootstrap.tsx
> +	clientContentUrl: "/config/content.json"  // 絶対パスを渡すとそれがPlayのclientContentUrlとしてサーバーに記録され全クライアントでそのURLが使われることになるのでここでは相対パスを渡す。
あ、、間違えてました。。修正しておきます

2019-02-05 07:15 UTC, yu-ogi approved these changes

2019-02-05 11:23 UTC, xnv approved these changes

2019-02-05 11:23 UTC, xnv commented on src/server/controller/ConfigController.ts
> +			const hostname = serverGlobalConfig.useRequestedHostname ? serverGlobalConfig.hostname : urlInfo[0];
単にもっとクリアな名前を使えばいいのでは。 `useGivenHostname` とか `useSpecifiedHostname` とか。

2019-02-06 03:36 UTC, dera- commented on src/server/controller/ConfigController.ts
> +			const hostname = serverGlobalConfig.useRequestedHostname ? serverGlobalConfig.hostname : urlInfo[0];
以下のように修正しようと思います
* useRequestedHostname => useGivenHostname
* useRequestedPort => useGivenPort

2019-02-06 04:06 UTC, xnv commented on src/server/index.ts
> +			console.warn("can not guarantee operation on port 80");
- listen の前にチェックしないとエラーになってこの警告出す前に EACCESS で死んじゃうような気がします
- "cannot guarantee" というよりは、EACCESS の説明になる方が嬉しい気がするので、より具体的に "Trying to listen on port XX. Listening well-known ports may be blocked by your operating system." とかですかねえ。

2019-02-06 04:16 UTC, xnv commented on src/server/index.ts
> +			console.warn("can not guarantee operation on port 80");
"cannot guarantee" よりはもう少し具体的に書きたいです。 "Akashic Serve is a development server which is not appropriate for public release. We do not recommend listen on a well-known port XX." ぐらいですかねえ。

2019-02-06 05:45 UTC, merged